In [1]:
import pandas as pd


In [5]:
data=pd.read_csv("train.csv")

In [29]:
data

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [14]:
data=data.dropna()

In [17]:
X= data.drop('label', axis=1)

In [18]:
Y= data['label']

In [23]:
import tensorflow as tf

In [25]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [26]:
voc_size=5000

In [27]:
messages= X.copy()

In [39]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [33]:
messages.reset_index(inplace=True)

In [41]:
import nltk
import re
from nltk.corpus import stopwords

In [42]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\19176\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [47]:
# Data Preprocessing

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus=[]
for i in range(0, len(messages)):
  
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
   

In [48]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [49]:
one_hot_repre= [one_hot(words,voc_size) for words in corpus]
one_hot_repre

[[2990, 3678, 3016, 2699, 1539, 2918, 688, 4820, 2205, 1499],
 [824, 2995, 3701, 2292, 1889, 1062, 4333],
 [3637, 2596, 3526, 2333],
 [1586, 2049, 1933, 2175, 2818, 492],
 [2606, 1889, 3623, 2206, 4730, 1766, 1889, 2599, 4225, 4204],
 [1966,
  4934,
  3596,
  3250,
  271,
  2306,
  3524,
  4254,
  4057,
  36,
  4441,
  3947,
  3499,
  517,
  4333],
 [2655, 381, 1408, 345, 2673, 1092, 3922, 2632, 2454, 2383, 2498],
 [4382, 291, 3114, 3957, 2686, 4280, 2306, 2187, 2454, 2383, 2498],
 [3016, 1593, 937, 1421, 1897, 1701, 132, 1915, 2306, 594],
 [4268, 3416, 3593, 1158, 4826, 3161, 2312, 1477],
 [4423, 2294, 743, 3832, 3807, 2549, 3724, 2404, 2156, 4521, 3812],
 [2175, 955, 1539, 1701, 2306, 2686],
 [4924, 4727, 4141, 2984, 551, 1417, 1786, 1147, 66],
 [2557, 1831, 2372, 1018, 1009, 4452, 218, 2454, 2383, 2498],
 [3862, 1130, 1377, 4377, 1248, 2454, 2383, 2498],
 [1397, 3724, 2749, 3713, 1642, 2487, 1385, 2433, 1997, 4950],
 [607, 3957, 2995],
 [18, 4002, 1449, 851, 2306, 960, 4136, 4333],


In [50]:
# Embedding representation

In [54]:
sent_length=20
embedded_docs= pad_sequences(one_hot_repre, padding='pre', maxlen= sent_length)
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2990,
       3678, 3016, 2699, 1539, 2918,  688, 4820, 2205, 1499])

In [55]:
# Creating Model

In [56]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [97]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

In [98]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [99]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [100]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 5s 28ms/step - loss: 0.0028 - accuracy: 0.9993 - val_loss: 0.6217 - val_accuracy: 0.9070
Epoch 2/10
192/192 [==============================] - 5s 25ms/step - loss: 0.0018 - accuracy: 0.9997 - val_loss: 0.6135 - val_accuracy: 0.9123
Epoch 3/10
192/192 [==============================] - 5s 24ms/step - loss: 0.0012 - accuracy: 0.9998 - val_loss: 0.7408 - val_accuracy: 0.9009
Epoch 4/10
192/192 [==============================] - 6s 32ms/step - loss: 2.7299e-04 - accuracy: 1.0000 - val_loss: 0.7028 - val_accuracy: 0.9074
Epoch 5/10
192/192 [==============================] - 6s 34ms/step - loss: 1.0819e-04 - accuracy: 1.0000 - val_loss: 0.7646 - val_accuracy: 0.9080
Epoch 6/10
192/192 [==============================] - 6s 33ms/step - loss: 6.2529e-05 - accuracy: 1.0000 - val_loss: 0.7760 - val_accuracy: 0.9090
Epoch 7/10
192/192 [==============================] - 6s 33ms/step - loss: 4.4360e-05 - accuracy: 1.0000 - val_loss: 0.7948 - val_

In [122]:

y_pred = (model.predict(X_test) > 0.5).astype("int32")
y_pred


189/189 [==============================] - 1s 5ms/step


array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [1]])

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9095277547638774

In [110]:
from sklearn.metrics import confusion_matrix

In [111]:
confusion_matrix(y_test,y_pred)

array([[3136,  283],
       [ 263, 2353]], dtype=int64)